require('config.colorscheme')
require('config.completion')
require('config.fugitive')
require('config.autopairs')
require('config.cmp')
require('config.lsp-colors')
require('config.lualine')
require('config.treesitter')
require('config.web-devicons')
require('config.nightfox')
require('config.lsp')
require('config.telescope')
require('config.netrw')
require('config.norg')
require('config.flutter-tools')
require('config.dashboard')
-- require('config.lsp-saga')
